In [ ]:
import tkinter as tk
from tkinter import ttk
from tkinter import filedialog as fd
from PIL import Image, ImageTk

import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

In [18]:
# val_data
validate_data = tf.keras.preprocessing.image_dataset_from_directory(
  './data/Vegetable Images/train',
  labels='inferred',
  image_size=(180, 180),
  label_mode='categorical',
  interpolation='bilinear',
  validation_split=0.020,
  subset="validation",
  seed=1234,
  color_mode='rgb'
)

class_name = validate_data.class_names

Found 5000 files belonging to 5 classes.
Using 100 files for validation.


In [ ]:
def select_file():
  print("Select file")
  filetype=(("image file", "*.jpg"), ("All file", "*.*"))
  fn = fd.askopenfilename(filetypes=filetype, initialdir="./data/Vegetable Images/train")

  if len(fn):
    img = Image.open(fn)
    img = img.resize((180, 180))
    pic = ImageTk.PhotoImage(img)
    imgLabel.config(image=pic)
    imgLabel.image = pic

  print(fn)

  myImage = tf.keras.utils.load_img(
    fn,
    color_mode='rgb',
    target_size=(180, 180),
    interpolation='nearest',
    keep_aspect_ratio=False
  )

  input_arr = tf.keras.utils.img_to_array(myImage)
  input_arr = np.array([input_arr])

  # Predict
  predict_value = myModel.predict(input_arr)
  result = np.argmax(predict_value[0])
  print(predict_value, result, class_name[result])

  txtLabel.config(text="{0}".format(class_name[result]))

In [22]:
myModel = tf.keras.models.load_model("Best.keras")

root = tk.Tk()
root.title("Demo App")
root.geometry("300x300")

img = ImageTk.PhotoImage(file="./data/Vegetable Images/train/Broccoli/0001.jpg")
imgLabel = ttk.Label(root, image=img)
imgLabel.pack()

txtLabel = ttk.Label(root, text="Predict Result")
txtLabel.pack()

openBtn = ttk.Button(root, text="Open file", command=select_file)
openBtn.pack()

root.mainloop()

Select file
C:/Users/Poorin/Documents/KMUTNB/Project Practice (GitHub)/data-image-processing/2025-09-23/data/Vegetable Images/train/Bean/0028.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 323ms/step
[[9.9999988e-01 7.7992183e-08 4.4830595e-10 9.8578337e-09 3.6973760e-10]] 0 Bean
Select file
C:/Users/Poorin/Documents/KMUTNB/Project Practice (GitHub)/data-image-processing/2025-09-23/data/Vegetable Images/train/Broccoli/0002.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
[[5.3179761e-12 2.7342659e-12 4.8619024e-09 1.1086376e-12 1.0000000e+00]] 4 Broccoli
Select file
C:/Users/Poorin/Documents/KMUTNB/Project Practice (GitHub)/data-image-processing/2025-09-23/data/Vegetable Images/train/Brinjal/0017.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
[[6.1635448e-09 1.2781289e-06 5.1110086e-04 9.9948680e-01 7.0269181e-07]] 3 Brinjal
Select file
C:/Users/Poorin/Documents/KMUTNB/Project Practice (GitHub)/data-image-processing/2025-09-23/data/Vegetable Images/train/Bitter_Gourd/0007.jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/